### ISSUE TITLE
I have tried the code you provided but all testcases are failed

### ISSUE THREAD

**Issue by vaishnavimaruvada** [MBhargavi235/TechEra-ReactJs-INTERVIEW-MOCK-TEST-1C#1]
``

**Comment by vaishnavimaruvada** [comment]
``

**Comment by BhargaviRM** [comment]
use normal html components instead of style.js

https://github.com/MBhargavi235/TechEra-ReactJs-INTERVIEW-MOCK-TEST-1C/tree/main

in this i added in the comments /* */ i added code use that, only use the comments code

**Comment by BhargaviRM** [comment]
> ``

use normal html components instead of style.js

https://github.com/MBhargavi235/TechEra-ReactJs-INTERVIEW-MOCK-TEST-1C/tree/main

in this i added in the comments /* */ i added code use that, only use the comments code

**Comment by vaishnavimaruvada** [comment]
thank you its working can you please provide solution for tavel guide react js

**Comment by krishnaveniKanchala** [comment]
Can you please provide react hooks coding practices
